### ISSUE TITLE
Integrate Grade Report

### ISSUE THREAD

**Issue by JimothyGreene** [DayInReview/day-in-review#14]
This is mainly something that I just want to have since I wanted to make my grade report app have a GUI and this could be a good way to do it. I think it could be a useful tool for this productivity suite. Thoughts @ishan0102?

**Comment by ishan0102** [comment]
Yeah it would be pretty sick, especially if we could integrate the Canvas API somehow.

**Comment by JimothyGreene** [comment]
Yeah that would be an interesting project. Wonder if Quest and/or Gradescope have public APIs. Those are the main other 2 places where my grades go.
